# Generated by Django 2.2.15 on 2020-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_remove_myuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='myuser',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
